# Generated by Django 3.1.5 on 2021-12-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Link to the website')),
                ('title', models.CharField(help_text='A title for this result.', max_length=500)),
                ('short_description', models.CharField(help_text='A short summary of this.', max_length=500)),
                ('keywords', models.TextField(help_text='Keywords which someone would search and it would show your result. Just put spaces to seperate keywords. E.g./ Cakerecipes Howtomakeacake')),
            ],
        ),
    ]
