# Generated by Django 3.1.5 on 2021-12-19 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchresult',
            name='keywords',
        ),
    ]
