# Generated by Django 3.1.5 on 2021-12-19 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_remove_searchresult_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchResult',
        ),
    ]
