# Generated by Django 3.1.5 on 2021-12-19 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('search', '0003_delete_searchresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(help_text='Link to the website')),
                ('title', models.CharField(help_text='A title for this result.', max_length=500)),
                ('short_description', models.CharField(help_text='A short summary of this.', max_length=500)),
                ('keyword1', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword2', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword3', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword4', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword5', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword6', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword7', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword8', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
                ('keyword9', models.CharField(help_text='Keywords which someone would search and it would show your result.E.g./ Cakerecipes', max_length=500)),
            ],
        ),
    ]
