# Generated by Django 3.1.5 on 2021-12-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20211219_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchresult',
            name='keyword1',
            field=models.CharField(help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword2',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword3',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword4',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword5',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword6',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword7',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword8',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='keyword9',
            field=models.CharField(blank=True, help_text='Keywords which someone would search and it would show your result. NO SPACES! E.g./ Cakerecipes', max_length=500),
        ),
    ]
